language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: unB+GS2255Lfm2gdVVro/igeLbq5EsrAKmAE14KkR6t9K21pAvmZIv5PuXAtsv9VeJw1cXoKsmwtDH8u2dSHruhoqt0BZCCsKG6VA5StJ9se9foxKc0q7rQTfskWsEs6TJ4c0F+bPHG6t54qWd4/GeWghTIXHRo6D3Nv3Uq31Wuo9VoEVUbj/OfHh8tUAWoFIxxCmNmkijMlROHhWqNwMDVUfgXwKn5WREwWw3u2tmeHruoCIN8b73u9EYsIWqezcnMl2TiZZrn6y2cBZU4hE/K/M0el0byyLrINL0dWMc1NTqsyqF6uruoTerXTcGZqHMlZLs10tCeK6HXHnYZ/94AOjfIffFAU3cu42A6nqXAgzCwjwbcMLOtNroi/5KeFhVrKRakjZRx99fv5S+O7oIEQOnhumdjQr/eMyTDKvLxUHjWnxkhkejkK1xuAbmIuzjQPxFDh7q5Jih1EbbrXM2vStkttTRZQtiInmen6a8Uq9lSilBESH5d8p7i/KMKC+XUY4PdOgheRaJtHuxQwJCZPRI79up3575lgtBA71xDdSbnejGY79e1gSZRwiD7aSQcgif5JLVm9X/TdmdlOauVvCv1FJkptLClQpykN08s0zuwctp4PkrKOLd/gc9UiBazTxribP9GxKyJFiZ7hfcX6u8bnhMTv74lQpt+Gg1k=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: oNsl2Ktb7AqLPmPPg20olw3syrDB0J5PBRcxrdJ2SMg4XWQTPwc9+fp/eEO86qN36eNAbJ66J5JFNzqXf4rDZKFv1tWLTKX9dh5zoKaIVaquQL1hsVKDNQay9ZLvEeK+//sGvxrnfCuAAlDZfFW/nLD9b1ZUGrcZLbo2w6JRTa7jZoAyJaOcxK5MUJw4emLqIWndvsbfZdWW3hDMm0dyah5tHh1zjDrZKiECHLmF4sRbOeDBtfVuKhTvrRW+45M/LbUtVyBPZNQNQbf6dssg6YIqb5NPFGOw/aMYHK3WklnF3fuQYPfZmQDPKqvBe2a1bgn5VxFz96BD1Wm4+iio4p57vxOpMKSB6BJlop+qRiDDB8OxdSiWoq/tb/lK663BOs6eMJqI3DhdhojpW/cW1GWl+Kbc0b2AE4UQegLQOVtjUiC9+QrGmjIVZ/K5UB4kHupiqiw4+gjA4gZUO5lv/oeOoyjmr7oKrmUHBcKDvKoiz12Blv3sKLTxPm4IvAfUN2qnc+O2Wf9woT5ddFlu7v1al08NwFK8sLlNxS0M9pd/xD6JbzJHL+5wUTJdy3uAcV/XD224MVCvgBrTJh8KLSAszJfy1CwHHG3Lt2H0TFQMVx16kkoZyTUh5uEbvgO7wQX2hV2f1ruhlVMTrB4CgW/k+ZaHRtasTayYnq4k6w0=
  - secure: fM3lU/cvIUfLqDgDpRAEkq5Qn4AoU00cj/OOYJp+XCN5Va2sGofTFfPKvmHp0elCXr/aKlm2WiX6QIafAIljHwJy6od15BRzviuZ+wOzMWGMvDfVOcHYGYDF7RdoNHmk/YiFCRtU7xsD25Wwmdv/JKQ2kiC8taiynapGNMUYLFRWC7duuCL1//+Gz4T4XFL4SrRYQUhTv3jKX7prr7j9yzlwwBgb06aR5bLilcKeEyAEpCN7ZeEC2SznBZjwi53d8F8LJ1BJFmOA8W7J/XQGdjC6cRI3udu0BYR++xsfMyGtZeQA6CJl0l26n1RyBDglnbmF4CYFdki/BZT8tlcoZak+8btfmqc/Hy3OhNqLuTliRHg4bGjDbB0ON/aFPMuzTglOXhCCi0UkL1hGTn4GB9L/CI+cYENxRtb1GTKNen3e+uCmQzk+m5IW2UqbsPAAwCzXovgmeSx5zy+PgvvQVcQiIZ072gjQ5GGY3he6NvtZFBMtlhhGyug1YxyFNNMYAJrj+apcafszXLXRx67eSypioQtNtl2PPXoJ8VT15OCGhFTqY6jlqP+KcZXq7Yoq/9V6rVexWnLH+XfJfsL4d+O8AccddjRCVTFcbUr2Kt4SRhJ5MNQM9pETgjlwauCLzaQSPJaE4/pnW06OvntWGILCb1GNo2LU6/ynBIYS54Y=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-enci-show-service:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
