# Package jar
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean','package','-Dmaven.test.skip=true']
# Build and tag the image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'src/main/docker/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/scc-show-service:${SHORT_SHA}', '.' ]
# Publish the image to Container Registry.
images:
- 'gcr.io/$PROJECT_ID/scc-show-service:${SHORT_SHA}'
options:
 machineType: 'N1_HIGHCPU_8'
 diskSizeGb: 200